# Generated by Django 5.2.3 on 2025-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
