# Generated by Django 5.2.3 on 2025-06-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGames', '0002_valoracion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
