# Generated by Django 5.2.3 on 2025-06-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGames', '0003_remove_valoracion_imagen_videojuego_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='user_email',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='user_name',
            field=models.CharField(default='UsuarioTest', max_length=50),
            preserve_default=False,
        ),
    ]
