# Generated by Django 5.2.4 on 2025-07-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_perfil_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar_predefinido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
