# Generated by Django 5.2.4 on 2025-07-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfil_avatar_predefinido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar_predefinido',
        ),
    ]
